# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d633c98437f6c1d28d4fd7c9d2bbdd8cf1c4a10db1a36088db9df8ef8966e4616dabcaf76754d06a64b6ec8e361c2c02135db5aec602341470e5855dcd0b28aa

test:
  secret_key_base: b1f07a6a280b832af5d3fa315c749f141a9721a6ab6c3603cfbf3eb92f0e61d7acace7a3c23e7a4d04174503c5e05f0730d51740d85174d162ea9cf6dbbd0fad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
